booking/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.about, name='about'),
]

techmentor/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('techmentorapp.urls', namespace='techmentorapp')),
    url(r'^admin/', admin.site.urls),
    url('^social/', include('social.apps.django_app.urls', namespace='social')),
    url('^auth/', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^sendgrid/', include('django_sendgrid.urls')),
    # url(r'^reserve/', include('booking.urls', namespace='booking')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

techmentorapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^mentor/(?P<id>[0-9]+)/$', views.mentor_detail, name='mentor_detail'),
    url(r'^mentor_list/$', views.mentor_list, name='mentor_list'),
    url(r'^edit_mentor/$', views.edit_mentor, name='edit_mentor'),
    url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^my_skill/$', views.my_skills, name='my_skills'),
    url(r'^edit_skill/edit/(?P<id>[0-9]+)/$', views.edit_skill, name="edit_skill"),
    url(r'^category/(?P<link>[\w|-]+)/$', views.category, name='category'),
    url(r'^search/$', views.search, name='search'),
    url(r'^add_skill/$', views.add_skill, name='add_skill'),
    url(r'^mentor/reserve/(?P<id>[0-9]+)/$', views.reserve, name='reserve'),
    url(r'^my_schedule/$', views.my_schedule, name='my_schedule'),
    url(r'^edit_schedule/(?P<id>[0-9]+)/$', views.edit_schedule, name='edit_schedule'),
    url(r'^create_schedule/$', views.create_schedule, name='create_schedule'),
    url(r'^mentor/reserve_check/(?P<id>[0-9]+)/(?P<mentor>[0-9]+)/$', views.reserve_check, name='reserve_check'),
    url(r'^thanks_page/$', views.thanks_page, name='thanks_page'),
    url(r'^infomation/$', views.infomation, name='infomation'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^company/$', views.company, name='company'),
    url(r'^privacy_policy/$', views.privacy_policy, name='privacy_policy'),
    url(r'^policy/$', views.policy, name='policy'),
]

techmentorapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from tinymce.models import HTMLField

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    avatar = models.FileField(upload_to='avatar')
    photo = models.FileField(upload_to='profile', blank=True)
    email = models.EmailField(max_length=255)

    def __str__(self):
        return self.user.username


class Mentor(models.Model):
    name = models.CharField(max_length=500)
    specialty = models.TextField()
    skill = models.ManyToManyField('Skill', through="Skill_Detail")
    about = models.TextField()
    description = models.TextField()
    performance = HTMLField()
    job = models.CharField(max_length=100, default="エンジニア")
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)

    mentor_time = models.DateTimeField(default=timezone.now)
    update_time = models.DateTimeField(auto_now=True)
    create_time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class Skill(models.Model):
    name = models.CharField(max_length=50)
    icon = models.FileField(upload_to='skills')
    link = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Skill_Detail(models.Model):
    mentor = models.ForeignKey('Mentor', related_name="mentor_info")
    skill = models.ForeignKey('Skill', related_name="skill_list")
    detail = models.TextField()
    experience = models.IntegerField(default=3)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.detail

class Available(models.Model):
    mentor = models.ForeignKey(Mentor)
    date = models.CharField(max_length=100)
    time = models.CharField(max_length=100)
    status = models.BooleanField(default=False)


class Review(models.Model):
    mentor = models.ForeignKey(Mentor)
    user = models.ForeignKey(User)
    content = models.TextField()

    def __str__(self):
        return self.content

class Reserve(models.Model):
    user = models.ForeignKey(User)
    mentor = models.ForeignKey(Mentor)
    text = models.TextField(default="")
    date_time = models.DateTimeField(auto_now=False)


class Infomation(models.Model):
    title = models.CharField(max_length=200)
    description = HTMLField()
    tag = models.CharField(max_length=100)
    date_time = models.DateTimeField(default=timezone.now)

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    subject = models.CharField(max_length=100)
    text = models.TextField()

techmentorapp/forms.py
from django import forms
from django.forms import ModelForm
from .models import Mentor, Profile, Skill_Detail, Reserve, Available, Contact
from tinymce.widgets import TinyMCE

class MentorForm(ModelForm):
    class Meta:
        model = Mentor
        fields = ['name', 'specialty', 'about', 'description', 'performance', 'status']

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'photo', 'email']

class SkillForm(ModelForm):
    class Meta:
        model = Skill_Detail
        fields = ['detail', 'experience', 'status']

class AddSkillForm(ModelForm):
    class Meta:
        model = Skill_Detail
        fields = ['skill', 'detail', 'experience', 'status']


class SomeForm(forms.Form):
    content = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))

class ReserveForm(ModelForm):
    class Meta:
        model = Reserve
        fields = ['user', 'mentor', 'text', 'date_time']

class ScheduleForm(ModelForm):
    class Meta:
        model = Available
        fields = ['date', 'time', 'status']

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'text']

techmentorapp/views.py
from django.shortcuts import render, redirect
from .models import Mentor, Skill_Detail, Profile, Review, Skill, Available, Infomation
from django.utils import dateformat
from django.contrib.auth.decorators import login_required
from .forms import MentorForm, ProfileForm, SkillForm, AddSkillForm, ScheduleForm, ContactForm
from datetime import datetime as dt
import string, random, datetime
import urllib.parse
from django.db.models import Q
from django.core.mail import send_mail
from django.core.paginator import (
    Paginator,  # ページネーター本体のクラス
    EmptyPage,  # ページ番号が範囲外だった場合に発生する例外クラス
    PageNotAnInteger  # ページ番号が数字でなかった場合に発生する例外クラス
)


# def _get_page(list_, page_no, count=1):
#     """ページネーターを使い、表示するページ情報を取得する"""
#     paginator = Paginator(list_, count)
#     try:
#         page = paginator.page(page_no)
#     except (EmptyPage, PageNotAnInteger):
#         # page_noが指定されていない場合、数値で無い場合、範囲外の場合は
#         # 先頭のページを表示する
#         page = paginator.page(1)
#     return page


# Create your views here.
def home(request):
    return render(request, 'home.html', {})

def mentor_detail(request, id):

    if request.method == "POST" and \
        not request.user.is_anonymous() and \
        'content' in request.POST and \
        request.POST['content'].strip() != '':
        Review.objects.create(content=request.POST['content'], mentor_id=id, user=request.user)

    try:
        mentor = Mentor.objects.get(id=id)
    except Mentor.DoesNotExist:
        return redirect('/')

    d = mentor.create_time
    create = dateformat.format(d, 'Y年 n月 d日')
    u = mentor.update_time
    update = dateformat.format(u, 'Y年 n月 d日')
    m = mentor.mentor_time
    mentime = dateformat.format(m, 'Y年 n月 d日')
    documents = Skill_Detail.objects.filter(status=True)

    url = request.get_full_path()
    parsed = urllib.parse.urlparse(url)
    params = urllib.parse.parse_qs(parsed.query)

    if not params:
        if mentor.user == request.user:
            return redirect('/mentor_list/')

    # mentor.mentor_time = 1
    # mentor.save()

    if request.user.is_anonymous() or \
        Review.objects.filter(mentor=mentor, user=request.user).count() > 0:
        show_post_review = False
    else:
        show_post_review = True #後で直す

    reviews = Review.objects.filter(mentor=mentor)
    return render(request, 'mentor_detail.html', {
        "mentor": mentor,
        "documents": documents,
        "create": create,
        "update": update,
        "mentime": mentime,
        "reviews": reviews,
        "show_post_review": show_post_review,
        "params": params,
    })


def mentor_list(request):
    info = Infomation.objects.all().order_by('-id')[:4]
    if not request.user.is_anonymous():
        mentors = Mentor.objects.all().exclude(user=request.user).exclude(status=False)
    else:
        mentors = Mentor.objects.all().exclude(status=False)
    page = request.GET.get('page')

    paginator = Paginator(mentors, 10)
    try:
        # mentors = _get_page(
        #     Mentor.objects.order_by('-id'),  # 投稿を新しい順に並び替えて取得する
        #     request.GET.get('page')  # GETクエリからページ番号を取得する
        # )

        paged_list = paginator.page(page)
    except PageNotAnInteger:
        paged_list = paginator.page(1)
    except EmptyPage:
        paged_list = paginator.page(paginator.num_pages)


    return render(request, 'mentor_list.html', {'mentors': paged_list, 'info': info})

@login_required(login_url="/")
def edit_mentor(request):
    try:
        mentor = Mentor.objects.get(user=request.user)
        error = ''
        if request.method == 'POST':
            mentor_form = MentorForm(request.POST, instance=mentor)
            if mentor_form.is_valid():
                mentor.save()
                success = "更新しました"
                # return redirect('/edit_mentor/')
                return render(request, 'edit_mentor.html', {'mentor': mentor, "error": error, "success": success})
            else:
                error = mentor_form.errors #"Data is not valid"

        return render(request, 'edit_mentor.html', {'mentor': mentor, "error": error})
    except Mentor.DoesNotExist:
        return redirect('/')

@login_required(login_url="/")
def edit_profile(request):
    try:
        profile = Profile.objects.get(user=request.user)
        error = ''
        if request.method == 'POST':
            profile_form = ProfileForm(request.POST, request.FILES, instance=profile)
            if profile_form.is_valid():
                # photoが空白だった場合は既存のまま
                # if not photo:
                #     profile.photo = photo
                profile.save()
                # return redirect('/edit_profile/')
                success = "更新しました"
                return render(request, 'edit_profile.html', {'profile': profile, "error": error, "success": success})
            else:
                error = profile_form.errors

        return render(request, 'edit_profile.html', {'profile': profile, "error": error})
    except Mentor.DoesNotExist:
        return redirect('/')


@login_required(login_url="/")
def my_skills(request):
    try:
        mentor = Mentor.objects.get(user=request.user)
        skills = Skill_Detail.objects.filter(mentor=mentor)
    except Skill_Detail.DoesNotExist:
        return redirect('/add_skill/')

    if request.method == 'POST':
        delete_ids = request.POST.getlist('delete_ids')
        if delete_ids:
            Skill_Detail.objects.filter(id__in=delete_ids).delete()
            delete = "削除しました"
            return render(request, 'my_skill.html', {"skills": skills, "delete": delete})
        else:
            error = "削除項目を選択してください"
        return render(request, 'my_skill.html', {"skills": skills, "error": error})

    return render(request, 'my_skill.html', {"skills": skills})


@login_required(login_url="/")
def add_skill(request):
    mentor = Mentor.objects.get(user=request.user)
    skills = Skill_Detail.objects.filter(mentor=mentor)
    error = ''
    add_skill = Skill.objects.all()
    # add_skill = Skill.objects.filter(~Q(name=skills))
    # Skill.objects.all().exclude(name=skills)
    skill_list = []
    for all in add_skill:
        skill_list.append(all)
        for not_need in skills:
            if all.name == not_need.skill.name:
                skill_list.pop()


    if request.method == 'POST':
        add_skill_form = AddSkillForm(request.POST)
        if add_skill_form.is_valid():
            skill = add_skill_form.save(commit=False)
            skill.mentor = mentor
            skill.save()
            # return redirect('/my_skill/')
            success = "スキルを追加しました"
            skills = Skill_Detail.objects.filter(mentor=mentor)
            return render(request, 'my_skill.html', {"skills": skills, "error": error, "success": success})
        else:
            error = "Data is not valid"
        return render(request, 'add_skill.html', {"error": error})
    add_skill_form = AddSkillForm()
    return render(request, 'add_skill.html', {"add_skill_form": add_skill_form, "error": error, "skill_list": skill_list})


@login_required(login_url="/")
def edit_skill(request, id):
    try:
        skill = Skill_Detail.objects.get(id=id)
        error = ''
        if request.method == 'POST':
            skill_form = SkillForm(request.POST, instance=skill)
            if skill_form.is_valid():
                skill.save()
                # return redirect('/my_skill/')
                success = "更新しました"
                return render(request, 'edit_skill.html', {'skill': skill, "error": error, "success": success})
            else:
                error = skill_form.errors

        return render(request, 'edit_skill.html', {'skill': skill, "error": error})
    except Mentor.DoesNotExist:
        return redirect('/')

def category(request, link):
    categories = {
        "html-css": "HTML & CSS",
        "javascript": "JavaScript",
        "php": "PHP",
        "python": "Python",
        "ruby-on-rails": "Ruby on Rails"
    }
    try:
        skill = Skill.objects.get(name=categories[link])
        # mentors = Mentor.objects.filter(skill=skill).exclude(user=request.user)
        if not request.user.is_anonymous():
            mentors = Mentor.objects.filter(skill=skill).exclude(user=request.user).exclude(status=False)
        else:
            mentors = Mentor.objects.filter(skill=skill).exclude(status=False)
        info = Infomation.objects.all().order_by('-id')[:4]
        # mentors = Mentor.objects.all()
    except Skill.DoesNotExist:
        return redirect('/')

    page = request.GET.get('page')

    paginator = Paginator(mentors, 10)
    try:
        paged_list = paginator.page(page)
    except PageNotAnInteger:
        paged_list = paginator.page(1)
    except EmptyPage:
        paged_list = paginator.page(paginator.num_pages)
    return render(request, 'mentor_list.html', {'mentors': paged_list, 'skill': skill, 'info': info})


def search(request):
    try:
        if not request.user.is_anonymous():
            mentors = Mentor.objects.filter(
                Q(specialty__contains=request.GET['title']) |
                # Q(skill__name__in=request.GET['title']) |
                Q(about__contains=request.GET['title']) |
                Q(job__contains=request.GET['title'])
            ).exclude(user=request.user).exclude(status=False)
        else:
            mentors = Mentor.objects.filter(
                Q(specialty__contains=request.GET['title']) |
                # Q(skill__name__in=request.GET['title']) |
                Q(about__contains=request.GET['title']) |
                Q(job__contains=request.GET['title'])
            ).exclude(status=False)
    except KeyError:
        return redirect('/')

    info = Infomation.objects.all().order_by('-id')[:4]
    page = request.GET.get('page')

    paginator = Paginator(mentors, 10)
    try:
        paged_list = paginator.page(page)
    except PageNotAnInteger:
        paged_list = paginator.page(1)
    except EmptyPage:

techmentorapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>Techmentor【テックメンター】</title>
    <link rel="shortcut icon" href="{% static 'img/common/532108815_fav.ico' %}">
    <meta name="keywords" content="テックメンター、techmentor">
    <meta name="description" content="プログラミングのメンターサポートなら「テックメンター(techmentor)」現役エンジニアがオンラインサポートします。">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
	<meta name="robots" content="noindex">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>


    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% block css %}{% endblock %}">
	{% block secondcss %}{% endblock %}
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/reveal.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.reveal.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/tinymce/tinymce.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/tinymce/config.js' %}"></script>

</head>
<body>
	<div id="myModal" class="reveal-modal">
		<h1 class="taC">ログイン／新規会員登録</h1>
		<ul class="social-login">
			<li>
				<a href="{% url 'social:begin' 'facebook' %}?next={{request.path}}" class="btn lg fb">
					<i class="fa fa-facebook"></i><span>Facebookでログイン／登録</span>
				</a>
			</li>
			<li>
				<a href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}" class="btn lg tw">
					<i class="fa fa-twitter"></i><span>Twitterでログイン／登録</span>
				</a>
			</li>
			<li>
				<a href="{% url 'social:begin' 'github' %}?next={{ request.path }}" class="btn lg git">
					<i class="fa fa-github"></i><span>Githubでログイン／登録</span>
				</a>
			</li>
			<!--<li>-->
				<!--<a href="" class="btn lg git">-->
					<!--<i class="fa fa-google-plus"></i><span>Googleでログイン／登録</span>-->
				<!--</a>-->
			<!--</li>-->
			<!--<li>-->
				<!--<div class="btn lg mail" data-modal="switch">-->
					<!--<i class="fa fa-envelope"></i><span>メールアドレスでログイン</span>-->
				<!--</div>-->
			<!--</li>-->
		</ul>
	</div>
	<header id="header" class="clearfix">
		<div class="container">
			<div class="flL">
				<h1 id="logo"><a href="/">TechMentor</a></h1>
				<nav id="g-nav">
					<ul>
						<li><a href="{% url 'techmentorapp:mentor_list' %}">メンターを探す</a></li>
						<li><a href="">β版公開中</a></li>
						<!--<li><a href="">使い方</a></li>-->
						<!--<li><a href="">Techmentorになる</a></li>-->
						<li>
							<form class="navbar-form navbar-left" role="search" method="GET" action="/search/">
								<div class="form-group">
									<div class="input-group">
										<input type="text" class="form-control" placeholder="キーワード" name="title">
										<span class="input-group-btn">
											<button class="btn btn-success">Find</button>
										</span>
									</div>
								</div>
							</form>
						</li>
					</ul>
				</nav>
			</div>

			<div class="flR">
				<ul id="signup" class="nav navbar-nav">
					{% if user and not user.is_anonymous %}
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"
							   role="button" area-haspopup="true" area-expanded="false">
								<img src="
								{% if user.profile %}
                                    {% if user.profile.photo %}
                                        https://s3-ap-northeast-1.amazonaws.com/techmentor-django-storage/{{ user.profile.photo }}
                                    {% else %}
                                    	{{ user.profile.avatar }}
                                    {% endif %}
								{% else %}
								    {% static 'img/common/icon.png' %}
								{% endif %}" class="img-circle" height="22" width="22">&nbsp;
								{{ user.profile.name|default:user.username }} <span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li><a href="{% url 'techmentorapp:edit_profile' %}">プロフィール</a></li>
								<li role="separator" class="divider"></li>
								{% if user.mentor %}
									<li><a href="{% url 'techmentorapp:edit_mentor' %}">メンター設定</a></li>
									<li role="separator" class="divider"></li>
									<li><a href="{% url 'techmentorapp:my_skills' %}">スキル設定</a></li>
									<li role="separator" class="divider"></li>
									<li><a href="{% url 'techmentorapp:my_schedule' %}">スケジュール</a></li>
									<li role="separator" class="divider"></li>
								{% endif %}
								<li><a href="{% url 'auth:logout' %}?next={{request.path}}">ログアウト</a></li>
							</ul>
						</li>
					{% else %}
						<li><a href="#" data-reveal-id="myModal">ログイン・新規会員登録</a></li>
					{% endif %}
				</ul>
			</div>
		</div>
	</header>
	<div id="category">
		<div class="container">
			<ul class="nav navbar-nav">
				<li><a href="/category/html-css">HTML & CSS</a></li>
				<li><a href="/category/javascript">JavaScript</a></li>
				<li><a href="/category/php">PHP</a></li>
				<li><a href="/category/ruby-on-rails">Ruby on Rails</a></li>
				<li><a href="/category/python">Python</a></li>
			</ul>
		</div>
	</div>

{% block page %}

{% endblock %}

	<footer id="footer">
		<div id="footerInner">
			<div class="flL sp-clearfix">
				<ul class="footer-menu">
					<li>
						<p class="title">人気のカテゴリー</p>
						<div class="disc">
							<p class=""><a href="/category/php">php</a></p>
							<p class=""><a href="/category/javascript">javascript</a></p>
							<p class=""><a href="/category/ruby-on-rails">Ruby on Rails</a></p>
							<p class=""><a href="/category/python">Python</a></p>
						</div>
					</li>
					<li>
						<p class="title">Techmentorについて</p>
						<div class="disc">
							<p class=""><a href="{% url 'techmentorapp:contact' %}">お問い合わせ</a></p>
							<p class=""><a href="{% url 'techmentorapp:privacy_policy' %}">プライバシーポリシー</a></p>
							<p class=""><a href="{% url 'techmentorapp:policy' %}">利用規約</a></p>
							<p class=""><a href="{% url 'techmentorapp:company' %}">運営会社</a></p>
						</div>
					</li>
				</ul>
			</div>

			<!--<div class="flR ajax-post">-->
				<!--<form action="/opinion/" class="mailform" id="OpinionIndexForm" method="post" accept-charset="utf-8">-->

					<!--<div class="controls">-->
						<!--<textarea name="opinion" placeholder="Techmentorについてご意見お聞かせください" cols="30" rows="6" id="OpinionBody"></textarea>-->
					<!--</div>-->
					<!--<button id="a_submit" class="btnSubmit">送信</button>-->
				<!--</form>-->

				<!--<div class="boxContact">-->
					<!--<p id="opinion-result"></p>-->
		            <!--<p>頂いたご意見への回答は行っておりません。</p>-->
		            <!--<p><a href="/contact/">返信の必要なお問い合わせはこちら</a></p>-->
		        <!--</div>-->
	        <!--</div>-->
		</div>
		<div class="container">
			<span>Techmentor &copy; 2016</span>
		</div>
	</footer>
</body>
</html>

techmentorapp/templates/info-right-column.html
            <div class="right-column">
				<div class="topics side-menu">
					<h2 class="heading">About</h2>
                    <ul>
                        <!--<li>-->
                            <!--<a href="">よくある質問</a>-->
                        <!--</li>-->
                        <li>
                            <a href="{% url 'techmentorapp:contact' %}">お問い合わせ</a>
                        </li>
                        <li>
                            <a href="{% url 'techmentorapp:privacy_policy' %}">プライバシーポリシー</a>
                        </li>
                        <li>
                            <a href="{% url 'techmentorapp:policy' %}">利用規約</a>
                        </li>
                        <li>
                            <a href="{% url 'techmentorapp:company' %}">運営会社</a>
                        </li>
                        <li>
                            <a href="{% url 'techmentorapp:infomation' %}">お知らせ</a>
                        </li>
                    </ul>
				</div>
			</div>

techmentorapp/templates/my_skill.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
	{% static 'css/mentor.css' %}
{% endblock %}

{% block page %}
    {% if error %}
        <div class="alert alert-warning alert-dismissible" role="alert">
            <div class="container">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <strong>Warning!</strong> {{ error }}
            </div>
        </div>
    {% elif success %}
        <div class="alert alert-success alert-dismissible" role="alert">
            <div class="container">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <strong>success：</strong> {{ success }}
            </div>
        </div>
    {% elif delete %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <div class="container">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <strong>delete：</strong> {{ delete }}
            </div>
        </div>
    {% endif %}

    <div id="customize-container">
        <div id="customize-contents">
            <div class="clearfix">
                <h1 style="margin-bottom: 30px" class="flL">スキル一覧</h1>
                <a href="{% url 'techmentorapp:add_skill' %}"><button type="button" class="btn btn-success btn-block flR" id="add">+スキルを追加する</button></a>
            </div>
            <div class="panel panel-default">
                <form method="post">
                    {% csrf_token %}
                    <table class="table table-bordered table-striped">
                        <thead class="bg-success">
                            <tr>
                                <th>
                                    <th>スキル名</th>
                                    <th>スキル詳細</th>
                                    <th>開発年数</th>
                                    <th>ステータス</th>
                                    <th></th>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for skill in skills %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td><a href="{% url 'techmentorapp:edit_skill' skill.id %}">{{ skill.skill.name }}</a></td>
                                    <td>{{ skill.detail }}</td>
                                    <td>{{ skill.experience }} 年</td>
                                    <td>{% if skill.status %}Active {% else %} Disabled {% endif %}</td>
                                    <td><input type="checkbox" name="delete_ids" value="{{ skill.id }}"></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                    <div class="form-group">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-success">削除</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}